### PR TITLE
PHP 8.1 while maintaining PHP 7.2 & 7.3 compatibility

### PR DESCRIPTION
**Pull request by swiffer**

### CODE REVIEW

**Comment by gildonei** [comment]
I think that in `SerializableEventTrait.php` in `serialize` and `unserialize` methods you could call `__serialize` and `__unserialize` reducing duplicated code

```php
/**
 * Returns the string representation of this object.
 *
 * @return string
 */
public function serialize()
{
    return $this->__serialize();
}

/**
 * Takes the string representation of this object so it can be reconstructed.
 *
 * @param string $data serialized string
 * @return void
 */
public function unserialize($data)
{
    $this->__unserialize($data);
}
```

**Comment by swiffer** [comment]
@gildonei  done ;)

**Comment by swiffer** [comment]
@lorenzo - can this get merged ?

**Comment by kyleweishaupt** [comment]
Is there anything that can be done to get this merged? I have tons of logs with the following message using PHP 8.1:

`AuditStash\Event\AuditUpdateEvent implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary)`

**Comment by gildonei** [comment]
Goodwill of Lorenzo to do the merge

**Comment by lorenzo** [comment]
sorry this took long

**Comment by swiffer** [comment]
@lorenzo thanks merging. As it was Part of master shouldn't this have been tagged as 3.1.0?🤔

**Comment by kyleweishaupt** [comment]
@lorenzo Thank you so much!

**Comment by lorenzo** [comment]
@swiffer thanks, released now

**Comment by swiffer** [comment]
> @swiffer thanks, released now

thanks!

**Pull request merged**
