### PR TITLE
Badges, travis, etc.

### PR DESCRIPTION
**Pull request by bravo-kernel**
Do not merge yet, work in progress. **Questions:**
- [x] what name do you want in the LICENSE file?
- [x] could you enable this repo in travis, styleci and codecov?

### CODE REVIEW

**Comment by lorenzo** [comment]
I can do that.

José Lorenzo Rodríguez

**Comment by lorenzo** [comment]
Btw, this is php 5.5+ only

**Comment by bravo-kernel** [comment]
Thanks, I will remove the 5.4

**Comment by bravo-kernel** [comment]
Ping @lorenzo, did you manage to enable 3 mentioned services?

**Comment by lorenzo** [comment]
Yeah, sorry... I forgot :D

**Comment by bravo-kernel** [comment]
This was not in mergeable state yet :scream:

**Comment by lorenzo** [comment]
I can help with the rest :)

**Comment by bravo-kernel** [comment]
ok, styleci badge in the readme needs the correct repo id, everything else I can create a new PR for.

**Comment by bravo-kernel** [comment]
And:
- correct travis badge link
- upload Initial code cov report

**Comment by lorenzo** [comment]
@bravo-kernel can you take care of making codecov run correctly?

**Comment by bravo-kernel** [comment]
OK, I will, could you generate and upload the initial report? https://github.com/cakephp/migrations/pull/194#issuecomment-181030963

**Comment by lorenzo** [comment]
Will do

**Comment by lorenzo** [comment]
@bravo-kernel I'm unable to do that locally, can you give me a hand? I'll send you the token via IRC

**Pull request merged**
